# Generated by Django 2.2.9 on 2020-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200419_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about_me',
            field=models.CharField(blank=True, max_length=150, verbose_name='About me'),
        ),
    ]
