# Generated by Django 2.2.9 on 2020-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usermodel_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_pic',
        ),
    ]
