# Generated by Django 2.2.9 on 2020-04-20 16:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=accounts.models.set_profile_Image_name, verbose_name='profile photo'),
        ),
    ]
