# Generated by Django 2.2.9 on 2020-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'UserModel', 'verbose_name_plural': 'UserModels'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='about_me',
            field=models.CharField(blank=True, default='I am a good person!', max_length=150, verbose_name='About me:'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='qualifications',
            field=models.CharField(blank=True, default="Bachelor's in Engineering", max_length=100, verbose_name='Your Qualifications'),
        ),
    ]
