# Generated by Django 3.0.5 on 2020-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200421_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark or Light Mode'),
        ),
    ]
