# Generated by Django 2.2.9 on 2020-04-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_product_product_tag'),
        ('accounts', '0002_auto_20200419_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Customer Questions')),
                ('questioned_date', models.DateTimeField(auto_now_add=True, verbose_name='Questioned on')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='product.Product', verbose_name='Questions on:')),
                ('user', models.ForeignKey(default='Guest Customer', on_delete=django.db.models.deletion.CASCADE, related_name='questioners', to='accounts.UserModel', verbose_name='Questioner')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Seller answer here!')),
                ('answered_date', models.DateTimeField(auto_now_add=True, verbose_name='Answered on')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_ans.Question', verbose_name='Answer for Qn.:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerers', to='accounts.UserModel', verbose_name='Admin or Seller')),
            ],
        ),
    ]
