# Generated by Django 2.2.9 on 2020-04-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_product_tag'),
        ('questions_ans', '0003_auto_20200420_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions_ans.Question', verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_prod', to='product.Product', verbose_name='Questions on:'),
        ),
    ]
