# Generated by Django 2.2.9 on 2020-04-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200419_1231'),
        ('product', '0007_product_product_tag'),
        ('questions_ans', '0004_auto_20200420_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionAns',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
