# Generated by Django 2.2.9 on 2020-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_ans', '0005_auto_20200420_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionans',
            name='description',
            field=models.TextField(verbose_name='Customer Questions'),
        ),
    ]
