# Generated by Django 2.2.9 on 2020-04-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200419_1231'),
        ('product', '0007_product_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Write your review here', verbose_name='Review')),
                ('rating', models.IntegerField(verbose_name='Ratings:')),
                ('reviewed_date', models.DateTimeField(auto_now_add=True, verbose_name='Reviewed on')),
                ('reviews', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_product', to='product.Product', verbose_name='Review on:')),
                ('user', models.ForeignKey(default='Guest Customer', on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='accounts.UserModel', verbose_name='Reviewer')),
            ],
        ),
    ]
