# Generated by Django 2.2.9 on 2020-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200420_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate1',
            field=models.IntegerField(default=0, verbose_name='Rating Count1:'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate2',
            field=models.IntegerField(default=0, verbose_name='Rating Count2:'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate3',
            field=models.IntegerField(default=0, verbose_name='Rating Count3:'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate4',
            field=models.IntegerField(default=0, verbose_name='Rating Count4:'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate5',
            field=models.IntegerField(default=0, verbose_name='Rating Count5:'),
        ),
    ]
