# Generated by Django 2.2.9 on 2020-04-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200420_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate4',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate5',
        ),
    ]
