# Generated by Django 3.0.5 on 2020-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200420_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Whether reviewd:'),
        ),
    ]
