# Generated by Django 3.0.5 on 2020-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Whether reviewed:'),
        ),
    ]
