# Generated by Django 2.2.9 on 2020-04-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grand Total')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Added On:')),
                ('product', models.ManyToManyField(blank=True, to='product.Product', verbose_name='Add to cart')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel', verbose_name='Cart Owner')),
            ],
        ),
    ]
