# Generated by Django 2.2.9 on 2020-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalSum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Grand Total with Taxes and service charges:'),
        ),
    ]
