# Generated by Django 2.2.9 on 2020-04-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_wishedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemCount',
            field=models.IntegerField(default=1, verbose_name='Item Count:'),
        ),
    ]
