# Generated by Django 2.2.9 on 2020-04-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0009_auto_20200416_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, verbose_name='Order ID:')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=80, max_digits=10, verbose_name='Shipping Charge:')),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Order Total:')),
                ('order_status', models.CharField(choices=[('Created', 'CREATED'), ('Paid', 'PAID'), ('Shipped', 'SHIPPED'), ('Refunded', 'REFUNDED')], default='Created', max_length=50, verbose_name='Order Status:')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Cart ID:')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
