# Generated by Django 2.2.9 on 2020-04-17 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Order Placed On:'),
            preserve_default=False,
        ),
    ]
